# Generated by Django 5.0.3 on 2024-05-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0002_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='original_name',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
