# Generated by Django 5.0.3 on 2024-03-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0002_alter_pdffile_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='pdffile',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='order',
            name='download_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(help_text='PDF file', upload_to='pdf_uploads'),
        ),
    ]
