# Generated by Django 5.0.3 on 2024-03-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0003_alter_order_options_alter_pdffile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='download_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
