services:
  app:
    build: .
    user: 1000:1000
    command: python3 /app/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=nl!kp$h8m%)g%!$kjb7i+fjoa-qdhb$r(g9bafgmnx(a+_)+tq
      - DEBUG=1
    volumes:
      - .:/app
    ports:
      - 8000:8000
