services:
  app:
    container_name: merger_backend
    build: .
    restart: always
    env_file: .env
    user: 1000:1000
    command: sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
